name: CI

on:
  push:

jobs:
  pre-commit:
    name: pre-commit
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install shellcheck
        run: sudo apt-get install shellcheck
      - uses: pre-commit/action@v3.0.0
        id: precommit
      - name: Upload pre-commit changes
        if: failure() && steps.precommit.outcome == 'failure'
        uses: rhaschke/upload-git-patch-action@main
        with:
          name: pre-commit

  ci:
    runs-on: ubuntu-latest
    env:
      REPO_PATH: ~/debs

    steps:
      - uses: actions/checkout@v3

      - name: Run exposed action
        uses: ./
        with:
          ROS_DISTRO: one
          ROS_SOURCES: .github/workflows/minimal.repos

      - name: Upload debs
        uses: actions/upload-artifact@v3
        with:
          name: debs
          path: ${{ env.REPO_PATH }}
