name: CI

on:
  push:

jobs:
  pre-commit:
    name: pre-commit
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install shellcheck
        run: sudo apt-get install shellcheck
      - uses: pre-commit/action@v3.0.0
        id: precommit
      - name: Upload pre-commit changes
        if: failure() && steps.precommit.outcome == 'failure'
        uses: rhaschke/upload-git-patch-action@main
        with:
          name: pre-commit

  ci:
    runs-on: ubuntu-latest
    env:
      REPO_PATH: ~/debs
      DEBUG_BASH: ${{ secrets.ACTIONS_STEP_DEBUG && 'true' || '' }}

    strategy:
      fail-fast: false
      matrix:
        DEB_DISTRO: [focal, jammy, bookworm ]
        ROS_DISTRO: [one]

    name: minimal-${{ matrix.DEB_DISTRO }}-${{ matrix.ROS_DISTRO }}
    steps:
      - uses: actions/checkout@v3

      - name: Run exposed action
        uses: ./
        with:
          DEB_DISTRO: ${{ matrix.DEB_DISTRO }}
          ROS_DISTRO: ${{ matrix.ROS_DISTRO }}
          ROS_SOURCES: .github/workflows/minimal.repos

      - name: Upload debs
        uses: actions/upload-artifact@v3
        with:
          name: minimal-${{ matrix.DEB_DISTRO }}-${{ matrix.ROS_DISTRO }}.debs
          path: ${{ env.REPO_PATH }}
