name: interactive

on:
  workflow_dispatch:
    # The inputs should not define a default value.
    # If they do, this value would be passed even if nothing is actually entered in the dialog,
    # thus overriding any configuration variables set, which should be considered in this case.
    # https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#onworkflow_dispatchinputs
    inputs:
      DEB_DISTRO:
        type: string
        required: true
        description: 'Ubuntu/Debian distro:'
        default: jammy
      ROS_DISTRO:
        type: string
        required: true
        description: 'ROS distribution codename:'
        default: one
      ROS_SOURCES:
        type: string
        description: 'ROS sources to compile:'
        required: true
        default: '*.repos'
      COLCON_PKG_SELECTION:
        type: string
        description: 'colcon package selection:'
        required: false
      SKIP_EXISTING:
        type: boolean
        description: Skip existing packages?
        required: false
      DEPLOY_MODE:
        type: choice
        description: How to deploy?
        required: true
        default: skip
        options:
          - skip
          - squash
          - append
      BRANCH:
        type: string
        description: 'Branch to use:'
        required: false

env:
  BRANCH: ${{ inputs.BRANCH || format('{0}-{1}', inputs.DEB_DISTRO, inputs.ROS_DISTRO) }}

jobs:
  build:
    name: ${{ inputs.DEB_DISTRO || vars.DEB_DISTRO || 'latest' }}-${{ inputs.ROS_DISTRO || vars.ROS_DISTRO || 'one'}}
    uses: ubi-agni/ros-builder-action/.github/workflows/generic.yaml@main
    with:
      DEB_DISTRO: ${{ inputs.DEB_DISTRO || vars.DEB_DISTRO }}
      ROS_DISTRO: ${{ inputs.ROS_DISTRO || vars.ROS_DISTRO || 'one' }}
      ROS_SOURCES: ${{ inputs.ROS_SOURCES || vars.ROS_SOURCES }}
      COLCON_PKG_SELECTION: ${{ inputs.COLCON_PKG_SELECTION || vars.COLCON_PKG_SELECTION || '' }}
      # proceed from existing debs artifact if run_attempt > 1
      DOWNLOAD_DEBS: ${{ github.run_attempt != '1' }}
      SKIP_EXISTING: ${{ inputs.SKIP_EXISTING || vars.SKIP_EXISTING || false}}

  deploy:
    needs: build
    runs-on: ubuntu-latest
    if: ( inputs.DEPLOY_MODE != 'skip' ) && vars.DEPLOY_URL

    env: # define common environment variables (cannot be passed from calling workflow)
      SEGMENT_DOWNLOAD_TIMEOUT_MINS: 10
      FOLDER: ${{ vars.DEBS_PATH || '~/debs' }}
      REPO: ${{ vars.DEPLOY_URL }}

    steps:
      - name: Download debs from build
        uses: actions/download-artifact@v3
        with:
          name: debs
          path: ${{ env.FOLDER }}

      - name: Deploy
        uses: s0/git-publish-subdir-action@v2.6.0
        env:
          SSH_PRIVATE_KEY: ${{ secrets.DEPLOY_PRIVATE_KEY }}
          MESSAGE: "${{ inputs.DEB_DISTRO }}-${{ inputs.ROS_DISTRO }} build"
          SQUASH_HISTORY: ${{ inputs.DEPLOY_MODE == 'squash' }}
